### ISSUE TITLE
Clean build of VMR results in failures to update installer.tasks.dll

### ISSUE THREAD

**Issue by ericstj** [dotnet/dotnet#3882]
Cloned VMR @ darc-main-7f028c67-b221-48c1-a5ba-08196aedecfa - 9e0f1268df9a28c470d87546bfe805edfe5bce7a
```
git clean -fxd .
build -c Release -os windows -arch x64  /p:VerticalName=Windows_x64
```

Failed with:
```
  C:\Program Files\dotnet\sdk\10.0.100\Microsoft.Common.CurrentVersion.targets(4903,5): error MSB3026: Could not copy "C:\src\dotnet\dotnet\src\runtime\artifacts\obj\installer.tasks\Release\net10.0\installer.tasks.dll" to "C:\src\dotnet\dotnet\src\runtime\artifacts\bin
  \installer.tasks\Release\net10.0\installer.tasks.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'C:\src\dotnet\dotnet\src\runtime\artifacts\bin\installer.tasks\Release\net10.0\installer.tasks.dll' because it is being used by another process. Th
  e file is locked by: ".NET Host (42448)" [C:\src\dotnet\dotnet\src\runtime\src\tasks\installer.tasks\installer.tasks.csproj::TargetFramework=net10.0]
```

**Comment by ViktorHofer** [comment]
Got fixed with https://github.com/dotnet/runtime/commit/891c183b22d023eea7bc4aa57dbc219d54852036

**Comment by ViktorHofer** [comment]
This got later fixed with https://github.com/dotnet/msbuild/commit/65d0f1a0ce346645108a9d82bf10f6a866ec730a. I noticed that a taskhostfactory didn't launch with the correct nodeReuse flag. The VMR (and runtime) needs to re-bootstrap to a newer SDK.

**Comment by ericstj** [comment]
Still reproducing on latest VMR.

```
 C:\src\dotnet\dotnet\.dotnet\sdk\11.0.100-preview.1.26078.121\Microsoft.Common.CurrentVersion.targets(4917,5): error MSB3026: Could not copy "C:\src\dotnet\dotnet\src\runtime\artifacts\obj\installer.tasks\Release\installer.tasks.dll" to "C:\src\dotnet\dotnet\src\runt
  ime\artifacts\bin\installer.tasks\Release\installer.tasks.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'C:\src\dotnet\dotnet\src\runtime\artifacts\bin\installer.tasks\Release\installer.tasks.dll' because it is being used by another process. T
  he file is locked by: ".NET Host (94476)" [C:\src\dotnet\dotnet\src\runtime\src\tasks\installer.tasks\installer.tasks.csproj]
```
Github preventing me from sharing a binlog, I'll share offline.

**Comment by ericstj** [comment]
As a workaround I can introduce a file rename step.  Libraries loaded can be renamed so long as nothing else took a more exclusive handle.

Here's what I tried:
```xml
  <Target Name="RenameOuputFileBeforeCopy" BeforeTargets="CopyFilesToOutputDirectory">
    <ItemGroup>
      <OutputFiles Include="$(TargetDir)$(TargetFileName)" />
      <OutputFiles Destination="%(RootDir)%(Directory)%(FileName).$([System.Guid]::NewGuid()).%(Extension)" />
      <OutputFilesExisting Include="@(OutputFiles)" Condition="Exists('%(OutputFiles.FullPath)')" />
    </ItemGroup>
    <!-- rename file to new file with guid appended -->
    <Move SourceFiles="@(OutputFilesExisting)" DestinationFiles="@(OutputFilesExisting->'%(Destination)')" />
    <!-- Would be nice to do this, but the warning is elevated to error by VMR
    <Delete Files="@(OutputFilesExisting->'%(Destination)')" TreatErrorsAsWarnings="true" ContinueOnError="true" /> -->
  </Target>
```
